version: '3'

services: 
  elasticsearch:
    build: elasticsearch
    environment: 
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xms512m"
    ports: 
      - 9200:9200
    volumes: 
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  
  kibana:
    build: kibana
    ports: 
      - 5601:5601
    volumes: 
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
